version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
   

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
        DB_HOST: db
        DB_USER: user
        DB_PASSWORD: password
        DB_NAME: tododb
    networks:
      - appnet
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      API_URL: http://backend:5000
    ports:
      - "3000:3000"
    networks:
      - appnet
    
volumes:
  pgdata:

networks:
  appnet:
  

